### ISSUE TITLE
Typo and missing props in `props-order`

### ISSUE THREAD

**Issue by wschulz-indeed** [yukukotani/eslint-plugin-chakra-ui#109]
There are a few props that are missing, and one misspelled. Specifically under `Padding` props.

The `paddingBottom` prop is spelled as `paddingButton` ([src](https://github.com/yukukotani/eslint-plugin-chakra-ui/blob/main/src/lib/getPriorityIndex.ts#L82))

The props `paddingX` and `paddingY` are missing. I know `px` and `py` exist, but it would be nice to have the full set of props.

The same is true for `marginX` and `marginY`.

**Comment by yukukotani** [comment]
Fixed in #115 and #118
