### ISSUE TITLE
Border color should have last priority

### ISSUE THREAD

**Issue by Netail** [yukukotani/eslint-plugin-chakra-ui#114]
When adding `borderColor` after `borderLeft` to the same component, the linter will move the `borderColor` before `borderLeft`. This results in the border using the initial color of the specified color.

Example (Results in a initial border as border-color is placed before border-left)
```tsx
<Flex borderColor='red' borderLeft='1px solid'>
  ...
</Flex>
```

**Comment by yukukotani** [comment]
@Netail Thanks for the reporting!

Could you try to fix this? We can achieve this by changing the order [here](https://github.com/yukukotani/eslint-plugin-chakra-ui/blob/main/src/lib/getPriorityIndex.ts#L206-L235).

**Comment by Netail** [comment]
> @Netail Thanks for the reporting!
> 
> Could you try to fix this? We can achieve it by changing the order [here](https://github.com/yukukotani/eslint-plugin-chakra-ui/blob/main/src/lib/getPriorityIndex.ts#L206-L235).

Sure, I'll take a look at it soon

**Comment by yukukotani** [comment]
Let's keep this opened until #134 is getting merged.
